Repository grails/grails-cache, pull requests merged in 2024-03, with the labels that each got.

#181 chore(build): fix 6.0.x CI
  .github/workflows/gradle.yml
  build.gradle
  gradle.properties
  src/integration-test/resources/GebConfig.groovy
Labels: type: ci

#185 feat(deps): Upgrade to Grails 6
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: feature, deps

#188 chore(ci): improve workflow configurations
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: maintenance, chore, ci, improvement

#180 chore(build): Migrate to Develocity build cache connector
  .github/workflows/gradle.yml
  settings.gradle
Labels: maintenance, chore, build, ci

#190 build(docs): update project build configuration to fix docs task
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: maintenance, bug, build, documentation

#192 chore(ci): update workflow configurations
  .github/release-drafter.yml
  .github/workflows/release-notes.yml
Labels: maintenance, chore, bug, build, ci, documentation

#193 chore(ci): improve release workflow configurations
  .github/workflows/release.yml
Labels: maintenance, chore, ci, improvement

#194 chore(build): only publish build scans for CI
  settings.gradle
Labels: maintenance, chore, build, ci

#195 refactor(build): update build configurations
  build.gradle
  gradle/docs.gradle
Labels: maintenance, build, refactor

#196 chore(ci): update java-ci workflow configurations
  .github/workflows/gradle.yml
  gradle/docs.gradle
Labels: maintenance, chore, ci

#197 chore(ci): update release workflow
  .github/workflows/release.yml
Labels: maintenance, chore, ci

#198 chore(ci): update release workflow configurations
  .github/workflows/release.yml
Labels: maintenance, chore, ci

#201 chore(ci): update release-drafter configurations
  .github/release-drafter.yml
Labels: maintenance, chore, ci
